module Evergreen.Migrate.V13 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V13.Types
import Evergreen.V9.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V9.Types.FrontendModel -> ModelMigration Evergreen.V13.Types.FrontendModel Evergreen.V13.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V9.Types.BackendModel -> ModelMigration Evergreen.V13.Types.BackendModel Evergreen.V13.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V9.Types.FrontendMsg -> MsgMigration Evergreen.V13.Types.FrontendMsg Evergreen.V13.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V9.Types.ToBackend -> MsgMigration Evergreen.V13.Types.ToBackend Evergreen.V13.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V9.Types.BackendMsg -> MsgMigration Evergreen.V13.Types.BackendMsg Evergreen.V13.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V9.Types.ToFrontend -> MsgMigration Evergreen.V13.Types.ToFrontend Evergreen.V13.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V9.Types.FrontendModel -> Evergreen.V13.Types.FrontendModel
migrate_Types_FrontendModel old =
    case old of
        Evergreen.V9.Types.Setup p0 ->
            Evergreen.V13.Types.Setup (p0 |> migrate_Types_SetupData)

        Evergreen.V9.Types.Ready p0 ->
            Evergreen.V13.Types.Ready (p0 |> migrate_Types_ReadyData)


migrate_Types_FrontendMsg : Evergreen.V9.Types.FrontendMsg -> Evergreen.V13.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V9.Types.UrlClicked p0 ->
            Evergreen.V13.Types.UrlClicked p0

        Evergreen.V9.Types.UrlChanged p0 ->
            Evergreen.V13.Types.UrlChanged p0

        Evergreen.V9.Types.SetupMsg p0 ->
            Evergreen.V13.Types.SetupMsg (p0 |> migrate_Types_SetupMsg)

        Evergreen.V9.Types.ReadyMsg p0 ->
            Evergreen.V13.Types.ReadyMsg (p0 |> migrate_Types_ReadyMsg)


migrate_Types_Mode : Evergreen.V9.Types.Mode -> Evergreen.V13.Types.Mode
migrate_Types_Mode old =
    case old of
        Evergreen.V9.Types.Paused ->
            Evergreen.V13.Types.Paused

        Evergreen.V9.Types.Running p0 ->
            Evergreen.V13.Types.Running (p0 |> migrate_Types_Player)


migrate_Types_Player : Evergreen.V9.Types.Player -> Evergreen.V13.Types.Player
migrate_Types_Player old =
    case old of
        Evergreen.V9.Types.Player1 ->
            Evergreen.V13.Types.Player1

        Evergreen.V9.Types.Player2 ->
            Evergreen.V13.Types.Player2


migrate_Types_ReadyData : Evergreen.V9.Types.ReadyData -> Evergreen.V13.Types.ReadyData
migrate_Types_ReadyData old =
    { key = old.key
    , player1Time = old.player1Time
    , player2Time = old.player2Time
    , mode = old.mode |> migrate_Types_Mode
    , lastTick = old.lastTick
    , increment = old.increment
    , lastSwitchedAt = old.lastSwitchedAt
    , vibrationEnabled = True
    }


migrate_Types_ReadyMsg : Evergreen.V9.Types.ReadyMsg -> Evergreen.V13.Types.ReadyMsg
migrate_Types_ReadyMsg old =
    case old of
        Evergreen.V9.Types.PlayerClicked p0 ->
            Evergreen.V13.Types.PlayerClicked (p0 |> migrate_Types_Player)

        Evergreen.V9.Types.Tick p0 ->
            Evergreen.V13.Types.Tick p0

        Evergreen.V9.Types.Pause ->
            Evergreen.V13.Types.Pause

        Evergreen.V9.Types.Reset ->
            Evergreen.V13.Types.Reset


migrate_Types_SetupData : Evergreen.V9.Types.SetupData -> Evergreen.V13.Types.SetupData
migrate_Types_SetupData old =
    { key = old.key
    , time = old.time
    , increment = old.increment
    , vibrationEnabled = True
    }


migrate_Types_SetupMsg : Evergreen.V9.Types.SetupMsg -> Evergreen.V13.Types.SetupMsg
migrate_Types_SetupMsg old =
    case old of
        Evergreen.V9.Types.PressedPlusMinute ->
            Evergreen.V13.Types.PressedPlusMinute

        Evergreen.V9.Types.PressedMinusMinute ->
            Evergreen.V13.Types.PressedMinusMinute

        Evergreen.V9.Types.PressedPlusTenSeconds ->
            Evergreen.V13.Types.PressedPlusTenSeconds

        Evergreen.V9.Types.PressedMinusTenSeconds ->
            Evergreen.V13.Types.PressedMinusTenSeconds

        Evergreen.V9.Types.AdjustedIncrementSlider p0 ->
            Evergreen.V13.Types.AdjustedIncrementSlider p0

        Evergreen.V9.Types.PressedStart ->
            Evergreen.V13.Types.PressedStart
